# Generated by Django 4.1.3 on 2022-11-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=128)),
                ('from_city', models.CharField(choices=[('#1', 'Lahore'), ('#2', 'Islamabad')], max_length=32)),
                ('receiver_name', models.CharField(max_length=128)),
            ],
        ),
    ]
