# Generated by Django 4.1.3 on 2022-11-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=16)),
                ('sender_name', models.CharField(max_length=128)),
                ('from_city', models.CharField(choices=[('#1', 'Lahore'), ('#2', 'Islamabad')], max_length=32)),
                ('sender_address', models.CharField(max_length=1024)),
                ('sender_phone', models.CharField(max_length=1024)),
                ('receiver_name', models.CharField(max_length=128)),
                ('to_city', models.CharField(choices=[('#1', 'Lahore'), ('#2', 'Islamabad')], max_length=32)),
                ('receiver_address', models.CharField(max_length=1024)),
                ('receiver_phone', models.CharField(max_length=1024)),
                ('insurance', models.BooleanField(default=False)),
            ],
        ),
    ]
