# Generated by Django 4.1.3 on 2022-11-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
