# Generated by Django 4.1.3 on 2022-11-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_status',
            field=models.CharField(choices=[('Lhr', 'Lahore'), ('Isl', 'Islamabad'), ('Rwp', 'Rawalpindi'), ('Mln', 'Multan'), ('Bwp', 'Bahawalpur'), ('Okr', 'Okara'), ('Ksr', 'Kasur'), ('Gjr', 'Gujranwala'), ('DGK', 'DG Khan'), ('Fbd', 'Faisalabad')], default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='from_city',
            field=models.CharField(choices=[('Lhr', 'Lahore'), ('Isl', 'Islamabad'), ('Rwp', 'Rawalpindi'), ('Mln', 'Multan'), ('Bwp', 'Bahawalpur'), ('Okr', 'Okara'), ('Ksr', 'Kasur'), ('Gjr', 'Gujranwala'), ('DGK', 'DG Khan'), ('Fbd', 'Faisalabad')], max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='order_id',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AlterField(
            model_name='item',
            name='to_city',
            field=models.CharField(choices=[('Lhr', 'Lahore'), ('Isl', 'Islamabad'), ('Rwp', 'Rawalpindi'), ('Mln', 'Multan'), ('Bwp', 'Bahawalpur'), ('Okr', 'Okara'), ('Ksr', 'Kasur'), ('Gjr', 'Gujranwala'), ('DGK', 'DG Khan'), ('Fbd', 'Faisalabad')], max_length=32),
        ),
    ]
