# Generated by Django 4.1.3 on 2022-11-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_item_current_status_alter_item_from_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Processing'), ('W', 'On Tte Way'), ('D', 'Delivered'), ('C', 'Cancelled')], default=1, help_text='Delivery Status', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='current_status',
            field=models.CharField(choices=[('Lhr', 'Lahore'), ('Isl', 'Islamabad'), ('Rwp', 'Rawalpindi'), ('Mln', 'Multan'), ('Bwp', 'Bahawalpur'), ('Okr', 'Okara'), ('Ksr', 'Kasur'), ('Gjr', 'Gujranwala'), ('DGK', 'DG Khan'), ('Fsd', 'Faisalabad')], help_text='Current Location', max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='from_city',
            field=models.CharField(choices=[('Lhr', 'Lahore'), ('Isl', 'Islamabad'), ('Rwp', 'Rawalpindi'), ('Mln', 'Multan'), ('Bwp', 'Bahawalpur'), ('Okr', 'Okara'), ('Ksr', 'Kasur'), ('Gjr', 'Gujranwala'), ('DGK', 'DG Khan'), ('Fsd', 'Faisalabad')], help_text='Sender', max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='receiver_address',
            field=models.CharField(help_text='Receiver', max_length=1024),
        ),
        migrations.AlterField(
            model_name='item',
            name='receiver_name',
            field=models.CharField(help_text='Receiver', max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='receiver_phone',
            field=models.CharField(help_text='Receiver', max_length=1024),
        ),
        migrations.AlterField(
            model_name='item',
            name='sender_address',
            field=models.CharField(help_text='Sender', max_length=1024),
        ),
        migrations.AlterField(
            model_name='item',
            name='sender_name',
            field=models.CharField(help_text='Sender', max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='sender_phone',
            field=models.CharField(help_text='Sender', max_length=1024),
        ),
        migrations.AlterField(
            model_name='item',
            name='to_city',
            field=models.CharField(choices=[('Lhr', 'Lahore'), ('Isl', 'Islamabad'), ('Rwp', 'Rawalpindi'), ('Mln', 'Multan'), ('Bwp', 'Bahawalpur'), ('Okr', 'Okara'), ('Ksr', 'Kasur'), ('Gjr', 'Gujranwala'), ('DGK', 'DG Khan'), ('Fsd', 'Faisalabad')], help_text='Receiver', max_length=32),
        ),
    ]
