# Generated by Django 4.1.3 on 2022-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_item_delivery_status_alter_item_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delivery_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], help_text='Delivery Status', max_length=32),
        ),
    ]
