# Generated by Django 4.1.3 on 2022-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_item_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=1024)),
                ('image', models.ImageField(upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='RateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=50)),
                ('to_city', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
